#+TITLE: WPC - Desktop and Lock Screen Wallpaper Setter
#+AUTHOR: Your Name
#+EMAIL: your.email@example.com
#+DATE: 2025-02-06

* Introduction

WPC (Wallpaper Changer) is a program that allows the user to set wallpapers for both the desktop and lock screen. It is a simple and easy-to-use application that lets you personalize your computer and make it more visually appealing.

The program supports various image formats and makes it easy to change the wallpaper with a user-friendly interface.

* Features

- Set wallpaper for the desktop.
- Set wallpaper for the lock screen.
- Support for common image formats (JPEG, PNG, BMP, etc.).
- Simple and intuitive GUI.

* COMMENT Installation

To install WPC, follow these steps:

#+begin_src bash
  git clone https://github.com/webdevred/wpc
  cd wpc
  make
  sudo make install
#+end_src

* Usage

You can create this config file in ~/.config/wpc/settings.json before you start the program.
If you do not create a config file then source directory will be set to your pictures directory in your home directory.

#+begin_src js
  {
      "sourceDirectoryPath" : "/mnt/HDD/backgrounds/",
      "monitorsWithBackgrounds": []
  }
#+end_src

1. Set Desktop Wallpaper:
   - Open the program by running wpc in your terminal
   - Browse to select an image file from your computer
   - The image will now applied for the correct monitor

2. Set Lock Screen Wallpaper:
   - Select the "Lock Screen" tab.
   - Follow the same process as the desktop wallpaper to select an image file or URL.

* System Requirements

- Requirements:
  - libxrandr-dev
  - libx11-dev
  - libgtk4-dev
  - libimlib2-dev
  - libcjson-dev
  - libmagickwand-6-headers

* License

WPC is licensed under the MIT License. See the LICENSE file for more information.
