name: C CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: clang-format -n -Werror src/*.c
      - run: clang-format -n -Werror include/*.h
      - run: clang-format -n -Werror nob.c
