name: Formatting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: clang-format -n -Werror src/*.c
      - run: clang-format -n -Werror include/**/*.h
      - run: clang-format -n -Werror nob.c
      - run: sudo apt install cpplint
#      - run: cpplint --filter=-build/include_subdir,-readability/casting src/*.c
